#访问http://localhost:6060/hystrix
server:
  port: 6060

spring:
  application:
    name: circuit-board
  security:
    user:
      name: root
      password: root


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
    metadata-map:
      user.name: "root"         #These two are needed so that the server
      user.password: "root" #can access the protected client endpoints
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8080/eureka
      ##,http://root:root@localhost:8001/eureka,http://root:root@localhost:8002/eureka

turbine:
  appConfig: system-service,opera-service,patch-service
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")

management:
  endpoints:
    web:
      exposure:
        include: "*"
  #        SpringBootActuator监控暴露所有接口
  endpoint:
    health:
      show-details: ALWAYS