spring:
  application:
    name: register
# 安全认证的配置
  security:
    user:
      name: root
      password: root

management:
  endpoints:
    web:
      exposure:
        include: "*"
#        SpringBootActuator监控暴露所有接口
  endpoint:
     health:
          show-details: ALWAYS

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
        #默认情况下，应用会向注册中心（也是它自己）注册它自己，设置为false表示禁止这种默认行为
    register-withEureka: false
        #表示不去检索其他的Eureka Server获取注册信息，因为服务注册中心本身的职责就是维护服务实例，它也不需要去检索其他服务
    fetch-registry: false
    service-url:
      defaultZone: http://root:root@localhost:8080/eureka/